version: "3.7"

services:
  web:
    image: tutum/hello-world
    ports:
      - 5000:80
    restart: always

        #	redis:
        #    image: redis/buster
        #    ports:
        #      - 6379:6379
